### ISSUE TITLE
Very narrow column in 999px wide window.

### ISSUE THREAD

**Issue by AndreasMadsen** [distillpub/post--memorization-in-rnns#16]
I don't know if it is intentional, but the text column at 999px is quite narrow and seems intended for mobile phone display. I understand that wide text is difficult to read, but there is easily space for the column wide used in a 1000px window and the column wide used in a 767px window is significantly wider.

**Comment by ludwigschubert** [comment]
I opted out of the medium-width size for your article! The text is so narrow because Distill articles can have sidenotes—yours doesn't have them, so it made sense to skip this narrow width. Fixed via 6a06087.

(Future versions of template won't have breakpoints in their styles and issues like this will hopefully not come up more often—so I just special cased it for now.)
